"""phase 2 platform hardening: audit log, soft delete

Revision ID: 2d4a9f348e62
Revises: 760ab8b2edad
Create Date: 2026-08-06 16:42:09.577886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4a9f348e62'
down_revision: Union[str, Sequence[str], None] = '760ab8b2edad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('appointments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medical_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'deleted_at')
    op.drop_column('medical_records', 'deleted_at')
    op.drop_column('doctors', 'deleted_at')
    op.drop_column('appointments', 'deleted_at')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
