"""referral platform domain extensions

Revision ID: 760ab8b2edad
Revises: c9a82a17b538
Create Date: 2026-08-06 16:24:57.854194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760ab8b2edad'
down_revision: Union[str, Sequence[str], None] = 'c9a82a17b538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('coverage_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_plans'))
    )
    op.create_index(op.f('ix_insurance_plans_id'), 'insurance_plans', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_availability_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_availability'))
    )
    op.create_index(op.f('ix_doctor_availability_id'), 'doctor_availability', ['id'], unique=False)
    op.create_table('doctor_insurance_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('insurance_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_insurance_networks_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['insurance_plan_id'], ['insurance_plans.id'], name=op.f('fk_doctor_insurance_networks_insurance_plan_id_insurance_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_insurance_networks'))
    )
    op.create_index(op.f('ix_doctor_insurance_networks_id'), 'doctor_insurance_networks', ['id'], unique=False)
    op.create_table('referral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('referring_doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('target_wait_days', sa.Integer(), nullable=True),
    sa.Column('preferred_location', sa.String(length=200), nullable=True),
    sa.Column('workflow_thread_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_referral_requests_patient_id_patients')),
    sa.ForeignKeyConstraint(['referring_doctor_id'], ['doctors.id'], name=op.f('fk_referral_requests_referring_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['specialist_id'], ['doctors.id'], name=op.f('fk_referral_requests_specialist_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_requests'))
    )
    op.create_index(op.f('ix_referral_requests_id'), 'referral_requests', ['id'], unique=False)
    op.create_table('referral_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=True),
    sa.Column('extracted_diagnosis_codes', sa.Text(), nullable=True),
    sa.Column('extracted_procedure_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], name=op.f('fk_referral_documents_referral_request_id_referral_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_documents'))
    )
    op.create_index(op.f('ix_referral_documents_id'), 'referral_documents', ['id'], unique=False)
    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_schedule_slots_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_schedule_slots_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_slots'))
    )
    op.create_index(op.f('ix_schedule_slots_id'), 'schedule_slots', ['id'], unique=False)
    op.create_table('specialist_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_request_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referral_request_id'], ['referral_requests.id'], name=op.f('fk_specialist_notes_referral_request_id_referral_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialist_notes'))
    )
    op.create_index(op.f('ix_specialist_notes_id'), 'specialist_notes', ['id'], unique=False)
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(op.f('uq_doctors_user_id'), 'doctors', ['user_id'])
    op.create_foreign_key(op.f('fk_doctors_user_id_users'), 'doctors', 'users', ['user_id'], ['id'])
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_patients_user_id'), 'patients', ['user_id'])
    op.create_foreign_key(op.f('fk_patients_user_id_users'), 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_patients_user_id_users'), 'patients', type_='foreignkey')
    op.drop_constraint(op.f('uq_patients_user_id'), 'patients', type_='unique')
    op.drop_column('patients', 'user_id')
    op.drop_constraint(op.f('fk_doctors_user_id_users'), 'doctors', type_='foreignkey')
    op.drop_constraint(op.f('uq_doctors_user_id'), 'doctors', type_='unique')
    op.drop_column('doctors', 'longitude')
    op.drop_column('doctors', 'latitude')
    op.drop_column('doctors', 'user_id')
    op.drop_index(op.f('ix_specialist_notes_id'), table_name='specialist_notes')
    op.drop_table('specialist_notes')
    op.drop_index(op.f('ix_schedule_slots_id'), table_name='schedule_slots')
    op.drop_table('schedule_slots')
    op.drop_index(op.f('ix_referral_documents_id'), table_name='referral_documents')
    op.drop_table('referral_documents')
    op.drop_index(op.f('ix_referral_requests_id'), table_name='referral_requests')
    op.drop_table('referral_requests')
    op.drop_index(op.f('ix_doctor_insurance_networks_id'), table_name='doctor_insurance_networks')
    op.drop_table('doctor_insurance_networks')
    op.drop_index(op.f('ix_doctor_availability_id'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_insurance_plans_id'), table_name='insurance_plans')
    op.drop_table('insurance_plans')
    # ### end Alembic commands ###
